Fix typo

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -31,9 +31,9 @@ jobs:
         run: |
           # find all instrumentations
           for d in instrumentations/opentelemetry-instrumentation-*; do
-            inst=$${d#*/opentelemetry-instrumentation-}
-            grep -q "odigos-opentelemetry-instrumentation-$$inst" setup.py \
-              || { echo "❌ setup.py missing odigos-opentelemetry-instrumentation-$$inst"; exit 1; }
+            inst=${d#*/opentelemetry-instrumentation-}
+            grep -q "odigos-opentelemetry-instrumentation-$inst" setup.py \
+              || { echo "❌ setup.py missing odigos-opentelemetry-instrumentation-$inst"; exit 1; }
           done
 
       - name: Build all instrumentations
diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -34,9 +34,9 @@ jobs:
       - name: Validate setup.py instrumentation lines
         run: |
           for d in instrumentations/opentelemetry-instrumentation-*; do
-            inst=$${d#*/opentelemetry-instrumentation-}
-            grep -q "odigos-opentelemetry-instrumentation-$$inst" setup.py \
-              || { echo "❌ setup.py missing odigos-opentelemetry-instrumentation-$$inst"; exit 1; }
+            inst=${d#*/opentelemetry-instrumentation-}
+            grep -q "odigos-opentelemetry-instrumentation-$inst" setup.py \
+              || { echo "❌ setup.py missing odigos-opentelemetry-instrumentation-$inst"; exit 1; }
           done
 
       - name: Build all instrumentations
@@ -48,8 +48,8 @@ jobs:
           TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
         run: |
           for d in instrumentations/opentelemetry-instrumentation-*; do
-            echo "➡️ Publishing $$(basename $$d)"
-            twine upload --non-interactive "$$d/dist/*"
+            echo "➡️ Publishing $(basename $d)"
+            twine upload --non-interactive "$d/dist/*"
           done
 
       - name: Build the package
